// Interface automatically generated by schemas-to-ts

export interface String {
  content?: string;
}
export interface String_Plain {
  content?: string;
}

export interface String_NoRelations {
  content?: string;
}

