// Interface automatically generated by schemas-to-ts

import { ProjectBriefInfo } from '../../../../components/project/interfaces/ProjectBriefInfo';
import { ProjectBriefInfo_Plain } from '../../../../components/project/interfaces/ProjectBriefInfo';
import { ProjectBriefInfo_NoRelations } from '../../../../components/project/interfaces/ProjectBriefInfo';

export interface PagePortfolio {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    projects: ProjectBriefInfo[];
  };
}
export interface PagePortfolio_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  projects: ProjectBriefInfo_Plain[];
}

export interface PagePortfolio_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  projects: ProjectBriefInfo_NoRelations[];
}

export interface PagePortfolio_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  projects: ProjectBriefInfo_Plain[];
}
