// Interface automatically generated by schemas-to-ts

import { ProjectFullInfo } from '../../../../components/project/interfaces/ProjectFullInfo';
import { ProjectFullInfo_Plain } from '../../../../components/project/interfaces/ProjectFullInfo';
import { ProjectFullInfo_NoRelations } from '../../../../components/project/interfaces/ProjectFullInfo';

export interface PagePortfilioDetail {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    projects: ProjectFullInfo[];
  };
}
export interface PagePortfilioDetail_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  projects: ProjectFullInfo_Plain[];
}

export interface PagePortfilioDetail_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  projects: ProjectFullInfo_NoRelations[];
}

export interface PagePortfilioDetail_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  projects: ProjectFullInfo_Plain[];
}
