// Interface automatically generated by schemas-to-ts

import { String } from '../../../../components/utilities/interfaces/String';
import { String_Plain } from '../../../../components/utilities/interfaces/String';
import { String_NoRelations } from '../../../../components/utilities/interfaces/String';

export interface PageProjectDetail {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    projectHeroImgURL?: string;
    projectTitle?: string;
    projectDescription?: string;
    projectCategories: String[];
    projectTechnologies: String[];
    projectLiveURL?: string;
    projectCtaContent?: string;
    projectBackgroundTitle?: string;
    projectBackgroundDescription?: string;
    projectStaticPreviewsTitle?: string;
    projectPreviewImgURLs: String[];
    slug?: string;
    projectDesignUrl?: string;
    projectDesignCtaContent?: string;
  };
}
export interface PageProjectDetail_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  projectHeroImgURL?: string;
  projectTitle?: string;
  projectDescription?: string;
  projectCategories: String_Plain[];
  projectTechnologies: String_Plain[];
  projectLiveURL?: string;
  projectCtaContent?: string;
  projectBackgroundTitle?: string;
  projectBackgroundDescription?: string;
  projectStaticPreviewsTitle?: string;
  projectPreviewImgURLs: String_Plain[];
  slug?: string;
  projectDesignUrl?: string;
  projectDesignCtaContent?: string;
}

export interface PageProjectDetail_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  projectHeroImgURL?: string;
  projectTitle?: string;
  projectDescription?: string;
  projectCategories: String_NoRelations[];
  projectTechnologies: String_NoRelations[];
  projectLiveURL?: string;
  projectCtaContent?: string;
  projectBackgroundTitle?: string;
  projectBackgroundDescription?: string;
  projectStaticPreviewsTitle?: string;
  projectPreviewImgURLs: String_NoRelations[];
  slug?: string;
  projectDesignUrl?: string;
  projectDesignCtaContent?: string;
}

export interface PageProjectDetail_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  projectHeroImgURL?: string;
  projectTitle?: string;
  projectDescription?: string;
  projectCategories: String_Plain[];
  projectTechnologies: String_Plain[];
  projectLiveURL?: string;
  projectCtaContent?: string;
  projectBackgroundTitle?: string;
  projectBackgroundDescription?: string;
  projectStaticPreviewsTitle?: string;
  projectPreviewImgURLs: String_Plain[];
  slug?: string;
  projectDesignUrl?: string;
  projectDesignCtaContent?: string;
}
