// Interface automatically generated by schemas-to-ts

import { ProjectFullInfo } from '../../../../components/project/interfaces/ProjectFullInfo';
import { ProjectFullInfo_Plain } from '../../../../components/project/interfaces/ProjectFullInfo';
import { ProjectFullInfo_NoRelations } from '../../../../components/project/interfaces/ProjectFullInfo';

export interface PageProjectDetail {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    project?: ProjectFullInfo;
    slug?: string;
    name?: string;
  };
}
export interface PageProjectDetail_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  project?: ProjectFullInfo_Plain;
  slug?: string;
  name?: string;
}

export interface PageProjectDetail_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  project?: ProjectFullInfo_NoRelations;
  slug?: string;
  name?: string;
}

export interface PageProjectDetail_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  project?: ProjectFullInfo_Plain;
  slug?: string;
  name?: string;
}
