// Interface automatically generated by schemas-to-ts

export interface PageContact {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    firstSectionTitle?: string;
    firstSectionParagraph?: string;
    secondSectionTitle?: string;
    firstFormFieldLabel?: string;
    firstFormFieldPlaceholder?: string;
    secondFormFieldLabel?: string;
    secondFormFieldPlaceholder?: string;
    thirdFormFieldLabel?: string;
    thirdFormFieldPlaceholder?: string;
    formSubmitButtonContent?: string;
  };
}
export interface PageContact_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  firstSectionTitle?: string;
  firstSectionParagraph?: string;
  secondSectionTitle?: string;
  firstFormFieldLabel?: string;
  firstFormFieldPlaceholder?: string;
  secondFormFieldLabel?: string;
  secondFormFieldPlaceholder?: string;
  thirdFormFieldLabel?: string;
  thirdFormFieldPlaceholder?: string;
  formSubmitButtonContent?: string;
}

export interface PageContact_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  firstSectionTitle?: string;
  firstSectionParagraph?: string;
  secondSectionTitle?: string;
  firstFormFieldLabel?: string;
  firstFormFieldPlaceholder?: string;
  secondFormFieldLabel?: string;
  secondFormFieldPlaceholder?: string;
  thirdFormFieldLabel?: string;
  thirdFormFieldPlaceholder?: string;
  formSubmitButtonContent?: string;
}

export interface PageContact_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  firstSectionTitle?: string;
  firstSectionParagraph?: string;
  secondSectionTitle?: string;
  firstFormFieldLabel?: string;
  firstFormFieldPlaceholder?: string;
  secondFormFieldLabel?: string;
  secondFormFieldPlaceholder?: string;
  thirdFormFieldLabel?: string;
  thirdFormFieldPlaceholder?: string;
  formSubmitButtonContent?: string;
}
