// Interface automatically generated by schemas-to-ts

import { Navigation } from '../../../../components/url/interfaces/Navigation';
import { Navigation_Plain } from '../../../../components/url/interfaces/Navigation';
import { Navigation_NoRelations } from '../../../../components/url/interfaces/Navigation';

export interface Layout {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    navigations: Navigation[];
    contactMeHeading?: string;
    contactMeURL?: string;
    contactMeButtonContent?: string;
  };
}
export interface Layout_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  navigations: Navigation_Plain[];
  contactMeHeading?: string;
  contactMeURL?: string;
  contactMeButtonContent?: string;
}

export interface Layout_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  navigations: Navigation_NoRelations[];
  contactMeHeading?: string;
  contactMeURL?: string;
  contactMeButtonContent?: string;
}

export interface Layout_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  navigations: Navigation_Plain[];
  contactMeHeading?: string;
  contactMeURL?: string;
  contactMeButtonContent?: string;
}
