// Interface automatically generated by schemas-to-ts

export interface Navigation {
  displayName?: string;
  url?: string;
}
export interface Navigation_Plain {
  displayName?: string;
  url?: string;
}

export interface Navigation_NoRelations {
  displayName?: string;
  url?: string;
}

