// Interface automatically generated by schemas-to-ts

export interface HomePage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    introHeading?: string;
    introCtaUrl?: string;
    introCtaContent?: string;
    aboutMeTitle?: string;
    aboutMeDescription?: string;
    aboutMeCtaUrl?: string;
    aboutMeCtaContent?: string;
    introImageURL?: string;
    aboutMeImageURL?: string;
  };
}
export interface HomePage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  introHeading?: string;
  introCtaUrl?: string;
  introCtaContent?: string;
  aboutMeTitle?: string;
  aboutMeDescription?: string;
  aboutMeCtaUrl?: string;
  aboutMeCtaContent?: string;
  introImageURL?: string;
  aboutMeImageURL?: string;
}

export interface HomePage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  introHeading?: string;
  introCtaUrl?: string;
  introCtaContent?: string;
  aboutMeTitle?: string;
  aboutMeDescription?: string;
  aboutMeCtaUrl?: string;
  aboutMeCtaContent?: string;
  introImageURL?: string;
  aboutMeImageURL?: string;
}

export interface HomePage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  introHeading?: string;
  introCtaUrl?: string;
  introCtaContent?: string;
  aboutMeTitle?: string;
  aboutMeDescription?: string;
  aboutMeCtaUrl?: string;
  aboutMeCtaContent?: string;
  introImageURL?: string;
  aboutMeImageURL?: string;
}
