// Interface automatically generated by schemas-to-ts

export interface ProjectBriefInfo {
  projectName?: string;
  projectDescription?: string;
  projectRelativeURL?: string;
  projectRelativeCtaContent?: string;
  projectThumbnailURL?: string;
}
export interface ProjectBriefInfo_Plain {
  projectName?: string;
  projectDescription?: string;
  projectRelativeURL?: string;
  projectRelativeCtaContent?: string;
  projectThumbnailURL?: string;
}

export interface ProjectBriefInfo_NoRelations {
  projectName?: string;
  projectDescription?: string;
  projectRelativeURL?: string;
  projectRelativeCtaContent?: string;
  projectThumbnailURL?: string;
}

