// Interface automatically generated by schemas-to-ts

import { String } from '../../utilities/interfaces/String';
import { String_Plain } from '../../utilities/interfaces/String';
import { String_NoRelations } from '../../utilities/interfaces/String';

export interface ProjectFullInfo {
  projectHeroImgURL?: string;
  projectTitle?: string;
  projectDescription?: string;
  projectCategories: String[];
  projectTechnologies: String[];
  projectLiveURL?: string;
  projectCtaContent?: string;
  projectBackgroundTitle?: string;
  projectBackgroundDescription?: string;
  projectStaticPreviewsTitle?: string;
  projectPreviewImgURLs: String[];
}
export interface ProjectFullInfo_Plain {
  projectHeroImgURL?: string;
  projectTitle?: string;
  projectDescription?: string;
  projectCategories: String_Plain[];
  projectTechnologies: String_Plain[];
  projectLiveURL?: string;
  projectCtaContent?: string;
  projectBackgroundTitle?: string;
  projectBackgroundDescription?: string;
  projectStaticPreviewsTitle?: string;
  projectPreviewImgURLs: String_Plain[];
}

export interface ProjectFullInfo_NoRelations {
  projectHeroImgURL?: string;
  projectTitle?: string;
  projectDescription?: string;
  projectCategories: String_NoRelations[];
  projectTechnologies: String_NoRelations[];
  projectLiveURL?: string;
  projectCtaContent?: string;
  projectBackgroundTitle?: string;
  projectBackgroundDescription?: string;
  projectStaticPreviewsTitle?: string;
  projectPreviewImgURLs: String_NoRelations[];
}

