// Interface automatically generated by schemas-to-ts

import { Media, Media_Plain } from "../common/Media";
import { AdminPanelRelationPropertyModification } from "../common/AdminPanelRelationPropertyModification";

export interface HomePage {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    introHeading?: string;
    introImage?: { data: Media };
    introCtaUrl?: string;
    introCtaContent?: string;
    aboutMeTitle?: string;
    aboutMeDescription?: string;
    aboutMeImage?: { data: Media };
    aboutMeCtaUrl?: string;
    contactMeTitle?: string;
    contactMeCtaUrl?: string;
  };
}
export interface HomePage_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  introHeading?: string;
  introImage?: Media_Plain;
  introCtaUrl?: string;
  introCtaContent?: string;
  aboutMeTitle?: string;
  aboutMeDescription?: string;
  aboutMeImage?: Media_Plain;
  aboutMeCtaUrl?: string;
  contactMeTitle?: string;
  contactMeCtaUrl?: string;
}

export interface HomePage_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  introHeading?: string;
  introImage?: number;
  introCtaUrl?: string;
  introCtaContent?: string;
  aboutMeTitle?: string;
  aboutMeDescription?: string;
  aboutMeImage?: number;
  aboutMeCtaUrl?: string;
  contactMeTitle?: string;
  contactMeCtaUrl?: string;
}

export interface HomePage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  introHeading?: string;
  introImage?: AdminPanelRelationPropertyModification<Media_Plain>;
  introCtaUrl?: string;
  introCtaContent?: string;
  aboutMeTitle?: string;
  aboutMeDescription?: string;
  aboutMeImage?: AdminPanelRelationPropertyModification<Media_Plain>;
  aboutMeCtaUrl?: string;
  contactMeTitle?: string;
  contactMeCtaUrl?: string;
}
